server:
  port: 8080

spring:
  application:
    name: Destinos Do Kite

  datasource:
    url: jdbc:mysql://localhost:3306/kitepoints_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true